### ISSUE TITLE
TypeError: unhashable type: 'dict' 

### ISSUE THREAD

**Issue by rayperkins1** [ctrueden/ibroadcast-python#1]
I am getting the above error when running the script.

I tried nothing and I'm all out of ideas.
```
ray@ubuntu20:~$ python3 integration.py
INFO:root:Please enter iBroadcast credentials:
Username: secret_but_valid@gmail.com
Password:
INFO:root:Logging in as secret_but_valid@gmail.com...
INFO:root:ok
INFO:root:Login successful - user_id: 2215312
INFO:root:Downloading library data...
Traceback (most recent call last):
  File "integration.py", line 19, in <module>
    ib = ibroadcast.iBroadcast(username, password, log)
  File "/home/ray/.local/lib/python3.8/site-packages/ibroadcast/ibroadcast.py", line 19, in __init__
    self._login(username, password)
  File "/home/ray/.local/lib/python3.8/site-packages/ibroadcast/ibroadcast.py", line 45, in _login
    self.refresh()
  File "/home/ray/.local/lib/python3.8/site-packages/ibroadcast/ibroadcast.py", line 91, in refresh
    self.albums = decode(self.library['library']['albums'])
  File "/home/ray/.local/lib/python3.8/site-packages/ibroadcast/util.py", line 75, in decode
    keymap = {v: k for (k, v) in data['map'].items()}
  File "/home/ray/.local/lib/python3.8/site-packages/ibroadcast/util.py", line 75, in <dictcomp>
    keymap = {v: k for (k, v) in data['map'].items()}
TypeError: unhashable type: 'dict'
ray@ubuntu20:~$ ^C
```

**Comment by ctrueden** [comment]
@rayperkins1 Thanks for the report. I also ran into this error recently, and it is fixed on the main branch actually; see 9bfb3855370d4b88c82cdc38116976051c3b262e. But I hadn't released it to PyPI yet. I have now done so as version 1.1.2.
